### ISSUE TITLE
The avg PSNR score is not good as you provided

### ISSUE THREAD

**Issue by pzz2011** [twtygqyy/pytorch-vdsr#13]
Hi,

I use the pretrained model you provided to test the PSRN, while I get the following result:

> bird_GT   31.572193470700064
> butterfly_GT   25.639481299833857
> head_GT 30.952934769252085
> woman_GT  28.067277003068586
> baby_GT  31.808729368688958

the average PSNR of Set5 is 29.60812318230871

**Comment by twtygqyy** [comment]
hi @pzz2011 Which script did you use for evaluation?

**Comment by pzz2011** [comment]
@twtygqyy I use the following command line:
python test.py --cuda to evaluate the images in the data folder

**Comment by twtygqyy** [comment]
@pzz2011 Please use mat format images https://github.com/twtygqyy/pytorch-LapSRN/tree/master/Set5 for more accurate result

**Comment by pzz2011** [comment]
thx.

**Comment by chaos5958** [comment]
@pzz2011 
Did you reproduce same result when using mat files? 
I wonder different implementation of bicubic lead to this much amount of performance gap. (e.g. ~ 2 dB of PSNR in x4)
