### ISSUE TITLE
Testing eval.py with provided model results in an error

### ISSUE THREAD

**Issue by ishmael1985** [twtygqyy/pytorch-vdsr#21]
While trying to run eval.py in Python 3 I get this error:

```
=> use gpu id: '0'
Traceback (most recent call last):
  File "eval.py", line 33, in <module>
    model = torch.load(opt.model, map_location=lambda storage, loc: storage)["model"]
  File "C:\Users\Ishmael\Anaconda3\envs\tensorflow\lib\site-packages\torch\serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\Ishmael\Anaconda3\envs\tensorflow\lib\site-packages\torch\serialization.py", line 420, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 918: ordinal not in range(128)
```

Is your model trained using Python 2?

**Comment by twtygqyy** [comment]
Hi @ishmael1985 Yes, the model was train with Python 2, please change the way of decoding to utf-8 and give a try.

**Comment by ishmael1985** [comment]
Easier said than done when on Anaconda Python 3 Windows 7, though I don't understand as the default decode for Python 3 is utf-8. It would be pretty much appreciated if you can provide a model that's a little friendlier for my setup.

**Comment by twtygqyy** [comment]
@ishmael1985 what if you use `model = torch.load(opt.model)["model"]`?
or please check out [this](https://discuss.pytorch.org/t/error-while-loading-saved-model-post-update-of-pytorch/14369/4) and [this](https://github.com/pytorch/text/issues/77)

**Comment by ishmael1985** [comment]
Works now, but I have to hack serialization.py by modifying line 418 unpickler = pickle_module.Unpickler(f, encoding='latin1').
Not the solution I'd prefer, but works for my purposes, thanks a lot.

**Comment by DouSong** [comment]
perfect @ishmael1985

**Comment by cvguet** [comment]
there is another solution is that train again in your PC

**Comment by wenyuqing** [comment]
为何我修改第418行unpickler = pickle_module.Unpickler（f，encoding ='latin1'）来破解serialization.py。还是出现这个错误？

**Comment by Wowkieling** [comment]
> 为何我修改第418行unpickler = pickle_module.Unpickler（f，encoding ='latin1'）来破解serialization.py。还是出现这个错误？

你现在解决这个问题了吗？

**Comment by ThreeSR** [comment]
Amazing! @ishmael1985
