### ISSUE TITLE
generate_train.m slow on 8G memory computer

### ISSUE THREAD

**Issue by blueardour** [twtygqyy/pytorch-vdsr#32]
Hi, @twtygqyy 

I'm running the generate_train.m to obtain the training set on my machine. It has only 8G DDR memory which seems to cause the script very slow to load data.

In the script, all patches are loaded in the memory first before save the h5 file. Is it possible to save data along fetching batches?

Or if it possible to share the generated file on net disk?

Thanks very much.

**Comment by twtygqyy** [comment]
@blueardour you can store the data in separate h5s and load them sequentially in the generator by modifying it. To match the paper's performance, I recommend  you to increase the memory.

**Comment by blueardour** [comment]
@twtygqyy  Thanks for your rely. I would follow your advice to find a more memory machine.
