### ISSUE TITLE
Problem of performance in PSNR on Set5

### ISSUE THREAD

**Issue by BUPTLdy** [twtygqyy/pytorch-vdsr#4]
I use the `model_epoch_50.pth` you provided in the `model` folder, the average PSNR on Set5 is [36.11, 32.28,  29.61] for scale x2, x3, x4, which is lower than the PSNR in the readme.
And I retrain the model by using default parameter, and the PSNR is even worse than bicubic.
Thank you.

**Comment by twtygqyy** [comment]
Hi @BUPTLdy, you should use matlab for image bicubic interpolation so as to achieve the best performance

**Comment by BUPTLdy** [comment]
The images in Set5 folder are bicubic interpolation from matlab or python?

**Comment by twtygqyy** [comment]
@BUPTLdy from matlab, but using mat format image could achieve the best performance.
you can find them here https://github.com/twtygqyy/pytorch-LapSRN/tree/master/Set5

**Comment by BUPTLdy** [comment]
Oh, I see, but can I use python to calculate PSNR by mat format bicubic interpolation from matlab?

**Comment by twtygqyy** [comment]
@BUPTLdy Yes, you can. Please check my test script here https://github.com/twtygqyy/pytorch-LapSRN/blob/master/test.py

**Comment by BUPTLdy** [comment]
Thank you.

**Comment by CHELSEA234** [comment]
@BUPTLdy 
Hi, did you get excepted result? Can you tell me how to do data augmentation here, I met a problem here...

**Comment by ZhangDY827** [comment]
@BUPTLdy 
Hi, i am doing research on super resolution. I want to get the expected average psnr on Set5 or Set14 using 
 bicubic interpolation. Firstly, I downsample the image with scipy.misc.imresize function 2X, then recover it to the original resolution with scipy.misc.imresize directly. But i get lower PSNR than expect scores. What`s wrong with it?

**Comment by BUPTLdy** [comment]
@CHELSEA234 
I used the data augmentation code which provided by here: https://github.com/Jongchan/tensorflow-vdsr/tree/master/data

**Comment by BUPTLdy** [comment]
@CasdDesnDR 
Actually, you should use the bicubic function provided by Matlab. Maybe you can reference this code: https://github.com/Jongchan/tensorflow-vdsr/blob/master/data/aug_test.m

**Comment by pzz2011** [comment]
@twtygqyy I don't know why using mat format image could achieve the best performance ? and 
why should we use matlab bicubic interpolation? (the bicubic implementation is different?)

**Comment by pzz2011** [comment]
@twtygqyy I don't know why using mat format image could achieve the best performance ? and 
why should we use matlab bicubic interpolation? (the bicubic implementation is different?)

**Comment by ZhangDY827** [comment]
@pzz2011 You can test  the result between jpg mat format image or other format. A little while ago, I directly 
calculate the PSNR from the jpg format using OPENCV,  not consistent with it using MATLAB.  To some extend, the results of Bicubic from OPENCV are not more accurate than  MATLAB.

**Comment by twtygqyy** [comment]
@pzz2011 (the bicubic implementation is different?) exactly! Check out https://stackoverflow.com/questions/22092744/what-is-the-difference-between-opencvs-and-matlabs-bicubic-algorithm
