### ISSUE TITLE
AssertionError when trying to run without CUDA

### ISSUE THREAD

**Issue by ghost** [twtygqyy/pytorch-vdsr#7]
When running test.py on an image with default parameters, the following is output:

```
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    model = torch.load(opt.model)["model"]
  File "/home/jack/.local/lib/python3.6/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/jack/.local/lib/python3.6/site-packages/torch/serialization.py", line 379, in _load
    result = unpickler.load()
  File "/home/jack/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 266, in _lazy_new
    _lazy_init()
  File "/home/jack/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/home/jack/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 58, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

You can see that I have torch installed locally, but I would not suppose that to be an issue. I'm curious as to why this torch.load() function would try to access CUDA when I haven't passed the --cuda argument to test.py. This could be a bug in PyTorch for all I know, but I think it's worth noting that I'm not using an NVIDIA GPU so I can't access CUDA to begin with. I have installed the recommended version of PyTorch for no CUDA, as well.

**Comment by twtygqyy** [comment]
Hi @scionicspectre. Have you tried to run the code with CPU mode? I don't have any experience to use PyTorch with GPU other than NVIDIA ones.

**Comment by ghost** [comment]
Thank you for the prompt response. As I understand it, all I should need to do to run it in CPU mode is not type '--cuda'. I have run a few PyTorch examples without CUDA on the CPU without issues. For some reason, it seems PyTorch is convinced test.py is trying to use CUDA. I'm fairly inexperienced with these libraries, so I hope you can forgive the sparse details.

**Comment by dshahrokhian** [comment]
Why would you close this issue without giving a solution?
